#ifndef CONFIG_SPRITES_SOLDADOS_H
#define CONFIG_SPRITES_SOLDADOS_H

#define SOLDADO_W	12
#define SOLDADO_H	13

#define SOLDADO_TIRO_W	2
#define SOLDADO_TIRO_H	9

#define VIDA_W 6
#define VIDA_H 6

extern const int INIMIGO_W[];
extern const int INIMIGO_H[];

#define INIMIGO_MENOR_W		INIMIGO_W[0]
#define INIMIGO_MENOR_H		INIMIGO_H[0]
#define INIMIGO_ESPADA_W	INIMIGO_W[1]
#define INIMIGO_ESPADA_H    INIMIGO_H[1]
#define INIMIGO_SNIPER_W	INIMIGO_W[2]
#define INIMIGO_SNIPER_H	INIMIGO_H[2]

#define INIMIGO_TIRO_W	4
#define INIMIGO_TIRO_H	4

#endif
